name: BocasLife
favicon: null
layout_spectrum: 0.3290396
typography_spectrum: 0.1736931
title: Living the dream of island life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1236675
  lightness: 0.5961214
  saturation: 0.7875211
  rhythmicContrast: 0.3707521
purpose: []
