layout_spectrum: 0.3290396
typography_spectrum: 0.1736931
color:
  saturation: 0.7875211
  brandStrength: 0.1236675
  lightness: 0.5961214
  rhythmicContrast: 0.3707521
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: BocasLife
